"""empty message

Revision ID: 4b34acb5f7c4
Revises: 28f82dcb42d9
Create Date: 2025-10-29 18:19:21.111627

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa


# revision identifiers, used by Alembic.
revision: str = "4b34acb5f7c4"
down_revision: Union[str, Sequence[str], None] = "28f82dcb42d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_event_event_id", "events", ["event_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_event_event_id", "events", type_="unique")
    # ### end Alembic commands ###
